export * from './common'
export { default as HomePage } from './Home'
export { default as CaseStudiesPage } from './CaseStudies'
export { default as AboutUsPage } from './AboutUs'
export { default as OnBoardingPage } from './OnBoardingPage'
export { default as OnBoardingStartPage } from './OnBoardingPage/OnBoardingStartPage'
export { default as PrivacyPolicyPage } from './PrivacyPolicyPage'
