export * from "./common"
export { default as HomePage } from "./Home"
export { default as CaseStudiesPage } from "./CaseStudies"
export { default as AboutUsPage } from "./AboutUs"
export { default as OnBoardingPage } from "./OnBoardingPage"